# config/application.yml

# Example environment variables
MY_API_KEY: "your-api-key"
SECRET_KEY_BASE: "your-secret-key"
DATABASE_USERNAME: "db-username"
DATABASE_PASSWORD: "db-password"




`figaro heroku:set -e production